Repository FRONTENDSCHOOL8/sunfish-EUID, pull requests merged in 2024-01, with the labels that each got.

#37 feat : RoundedButton 컴포넌트 마크업 및 스타일링
  src/components/RoundButton/index.html
Labels: 💎 Feature

#43 chore: swiper, gsap, pocketbase 패키치 설치
  package-lock.json
  package.json
Labels: 📃 Documentation

#51 Remotes/upstream/feat/device trading
  src/assets/exchangeIcon/close.svg
  src/assets/exchangeIcon/complete.svg
  src/assets/exchangeIcon/exchange.svg
  src/assets/exchangeIcon/heart.svg
  src/assets/exchangeIcon/plus.svg
  src/assets/exchangeIcon/project.svg
  src/assets/exchangeIcon/reservation.svg
  src/assets/exchangeIcon/study.svg
  src/pages/exchange/exchange.html
  src/pages/exchange/exchange.js
  tailwind.config.js
Labels: 💎 Feature

#55 feat : 게시판 메인, 같이해요, 같이해요글쓰기 페이지 구현
  src/assets/boardIcon/back.svg
  src/assets/boardIcon/calender_black.svg
  src/assets/boardIcon/direction_rotate.svg
  src/assets/boardIcon/hamburger.svg
  src/assets/boardIcon/lock_black.svg
  src/assets/boardIcon/map_black.svg
  src/assets/boardIcon/plus.svg
  src/assets/boardIcon/time_black.svg
  src/pages/board/board.js
  src/pages/board/index.html
  src/pages/board/together.html
  src/pages/board/together.js
  src/pages/board/writeTogether.html
  src/pages/board/writeTogether.js
Labels: 💎 Feature

#58 feat : plus button 컴포넌트 추가
  src/components/PlusButton/index.html
Labels: 💎 Feature

#66 refactor : 게시판 페이지 코드 리팩토링
  src/pages/board/board.js
  src/pages/board/index.html
  src/pages/board/together.html
  src/pages/board/together.js
  src/pages/board/writeTogether.html
  src/pages/board/writeTogether.js
Labels: 🐛 BugFix

#78 [feat: pockebase util함수 추가]
  src/lib/utils/index.js
  src/lib/utils/pb.js
Labels: 📃 Documentation

#74 feat : 같이해요 게시글 조회 페이지 구현
  src/assets/boardIcon/organizer.svg
  src/pages/board/togetherView.html
Labels: 💎 Feature

#75 feat : 게시판 질의응답 페이지 구현
  src/pages/board/qna.html
  src/pages/board/qna.js
Labels: 💎 Feature

#76 feat : 질의응답 글쓰기 페이지 구현
  src/assets/boardIcon/file.svg
  src/pages/board/writeQna.html
  src/pages/board/writeQna.js
Labels: 💎 Feature

#80 feat : 유효성 검사 인풋 컴포넌트 추가
  src/components/ValidationInput/ValidationInput.js
  src/components/ValidationInput/index.html
Labels: 💎 Feature

#85 refactor : 게시판 내 페이지들 리팩토링
  src/pages/board/index.html
  src/pages/board/togetherView.html
  src/pages/board/writeQna.html
  src/pages/board/writeQna.js
  src/pages/board/writeTogether.html
Labels: 🐛 BugFix

#87 모달 기능 추가
  src/components/Modal/Modal.js
  src/styles/modal.css
  src/styles/tailwind.css
Labels: 💎 Feature

#90 refactor : 게시판 내 페이지들 리팩토링
  src/pages/board/index.html
  src/pages/board/togetherView.html
  src/pages/board/writeQna.html
  src/pages/board/writeQna.js
  src/pages/board/writeTogether.html
Labels: 🐛 BugFix

#91 feat : 메인 페이지 구현
  src/assets/banner.png
  src/pages/main/index.html
  src/pages/main/main.js
Labels: 💎 Feature

#97 feat : 게시판 페이지 pocketbase 연동
  src/pages/board/board.js
  src/pages/board/index.html
  src/pages/board/qna.html
  src/pages/board/together.html
  src/pages/board/together.js
  src/pages/board/togetherView.html
  src/pages/board/togetherView.js
  src/pages/board/writeTogether.js
Labels: 💎 Feature

#98 [Js]기기거래
  src/assets/exchangeIcon/heart.svg
  src/assets/exchangeIcon/heart_full.svg
  src/assets/exchangeIcon/sharing.svg
  src/lib/animation/dice.js
  src/lib/dom/index.js
  src/lib/error/index.js
  src/lib/index.js
  src/lib/utils/comma.js
  src/lib/utils/getPbImageUrl.js
  src/lib/utils/index.js
  src/lib/utils/storage.js
  src/pages/exchange/exchange.js
  src/pages/exchange/exchangeData.js
  src/pages/exchange/exchangeDetail.html
  src/pages/exchange/exchangeDetail.js
  src/pages/exchange/exchangeWrite.html
  src/pages/exchange/exchangeWrite.js
  src/pages/exchange/index.html
  src/styles/scroll.css
  tailwind.config.js
Labels: 💎 Feature

#99 fix : pb 함수 util/index.js 내용에 없던 문제 수정
  src/lib/utils/index.js
Labels: 🐛 BugFix

#100 Feat : 게시판 추가 기능 구현
  src/assets/boardIcon/send.svg
  src/pages/board/qna.html
  src/pages/board/qna.js
  src/pages/board/qnaView.html
  src/pages/board/qnaView.js
  src/pages/board/together.js
  src/pages/board/togetherView.js
  src/pages/board/writeQna.html
  src/pages/board/writeQna.js
  src/pages/board/writeTogether.html
  src/pages/board/writeTogether.js
  src/styles/tailwind.css
  vite.config.js
Labels: 💎 Feature

#101 feat : 채팅기능 구현
  src/assets/chattingIcon/won.svg
  src/pages/board/qnaView.js
  src/pages/board/togetherView.js
  src/pages/board/writeTogether.js
  src/pages/chatting/lobby.html
  src/pages/chatting/lobby.js
  src/pages/chatting/room.html
  src/pages/chatting/room.js
Labels: 💎 Feature

#106 [JS]기기거래 페이지 점검
  src/pages/exchange/exchange.js
  src/pages/exchange/exchangeDetail.html
  src/pages/exchange/exchangeDetail.js
  src/pages/exchange/exchangeMake.html
  src/pages/exchange/exchangeMake.js
  src/pages/exchange/exchangeWrite.html
  src/pages/exchange/exchangeWrite.js
  src/pages/exchange/index.html
Labels: 💎 Feature

#110 [JS]기기거래 페이지 추가
  src/pages/exchange/exchange.js
  src/pages/exchange/exchangeData.js
  src/pages/exchange/exchangeDetail.html
  src/pages/exchange/exchangeDetail.js
  src/pages/exchange/exchangeMake.html
  src/pages/exchange/exchangeMake.js
  src/pages/exchange/exchangeWrite.js
  src/pages/exchange/index.html
Labels: 💎 Feature

#111 마이페이지 기능 구현
  src/components/ValidationInput/ValidationInput.js
  src/pages/myeuid/editProfile.html
  src/pages/myeuid/editProfile.js
  src/pages/myeuid/index.html
  src/pages/myeuid/index.js
  src/pages/myeuid/myProfile.html
  src/pages/myeuid/myProfile.js
Labels: 💎 Feature

#113 feat : 채팅로비 구현 refactor : 메인 및 게시판 페이지 리팩토링
  src/assets/boardIcon/send.svg
  src/assets/boardIcon/send_full.svg
  src/components/Modal/Modal.js
  src/lib/utils/checkAuth.js
  src/lib/utils/convertTime.js
  src/lib/utils/index.js
  src/pages/board/board.js
  src/pages/board/index.html
  src/pages/board/qna.html
  src/pages/board/qna.js
  src/pages/board/qnaView.html
  src/pages/board/qnaView.js
  src/pages/board/together.html
  src/pages/board/together.js
  src/pages/board/togetherView.html
  src/pages/board/togetherView.js
  src/pages/board/writeQna.html
  src/pages/board/writeQna.js
  src/pages/board/writeTogether.html
  src/pages/board/writeTogether.js
  src/pages/chatting/lobby.html
  src/pages/chatting/lobby.js
  src/pages/chatting/room.html
  src/pages/chatting/room.js
  src/pages/main/index.html
  src/pages/main/main.js
  src/styles/skeleton.css
  src/styles/tailwind.css
  tailwind.config.js
Labels: 🐛 BugFix, 💎 Feature

#129 Refactor/device trading
  src/pages/chatting/lobby.html
  src/pages/chatting/lobby.js
  src/pages/chatting/room.html
  src/pages/chatting/room.js
  src/pages/exchange/exchangeDetail.js
Labels: 💎 Feature
